[package]
name = "libthrob"
description = "A terminal throbber crate"
repository = "https://github.com/TheBunnyMan123/libthrob"
license = "Apache-2.0"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29.0", default-features = false, features = ["windows"] }

